/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HelpImport } from './routes/help'
import { Route as PublicImport } from './routes/_public'
import { Route as PublicIndexImport } from './routes/_public/index'
import { Route as PublicBlogImport } from './routes/_public/blog'
import { Route as PublicAboutImport } from './routes/_public/about'
import { Route as PublicBlogIndexImport } from './routes/_public/blog.index'
import { Route as PublicBlogSplatImport } from './routes/_public/blog.$'

// Create/Update Routes

const HelpRoute = HelpImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRoute,
} as any)

const PublicRoute = PublicImport.update({
  id: '/_public',
  getParentRoute: () => rootRoute,
} as any)

const PublicIndexRoute = PublicIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)

const PublicBlogRoute = PublicBlogImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => PublicRoute,
} as any)

const PublicAboutRoute = PublicAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)

const PublicBlogIndexRoute = PublicBlogIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicBlogRoute,
} as any)

const PublicBlogSplatRoute = PublicBlogSplatImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PublicBlogRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicImport
      parentRoute: typeof rootRoute
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpImport
      parentRoute: typeof rootRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutImport
      parentRoute: typeof PublicImport
    }
    '/_public/blog': {
      id: '/_public/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof PublicBlogImport
      parentRoute: typeof PublicImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexImport
      parentRoute: typeof PublicImport
    }
    '/_public/blog/$': {
      id: '/_public/blog/$'
      path: '/$'
      fullPath: '/blog/$'
      preLoaderRoute: typeof PublicBlogSplatImport
      parentRoute: typeof PublicBlogImport
    }
    '/_public/blog/': {
      id: '/_public/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof PublicBlogIndexImport
      parentRoute: typeof PublicBlogImport
    }
  }
}

// Create and export the route tree

interface PublicBlogRouteChildren {
  PublicBlogSplatRoute: typeof PublicBlogSplatRoute
  PublicBlogIndexRoute: typeof PublicBlogIndexRoute
}

const PublicBlogRouteChildren: PublicBlogRouteChildren = {
  PublicBlogSplatRoute: PublicBlogSplatRoute,
  PublicBlogIndexRoute: PublicBlogIndexRoute,
}

const PublicBlogRouteWithChildren = PublicBlogRoute._addFileChildren(
  PublicBlogRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicBlogRoute: typeof PublicBlogRouteWithChildren
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicBlogRoute: PublicBlogRouteWithChildren,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof PublicRouteWithChildren
  '/help': typeof HelpRoute
  '/about': typeof PublicAboutRoute
  '/blog': typeof PublicBlogRouteWithChildren
  '/': typeof PublicIndexRoute
  '/blog/$': typeof PublicBlogSplatRoute
  '/blog/': typeof PublicBlogIndexRoute
}

export interface FileRoutesByTo {
  '/help': typeof HelpRoute
  '/about': typeof PublicAboutRoute
  '/': typeof PublicIndexRoute
  '/blog/$': typeof PublicBlogSplatRoute
  '/blog': typeof PublicBlogIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_public': typeof PublicRouteWithChildren
  '/help': typeof HelpRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/blog': typeof PublicBlogRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_public/blog/$': typeof PublicBlogSplatRoute
  '/_public/blog/': typeof PublicBlogIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/help' | '/about' | '/blog' | '/' | '/blog/$' | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to: '/help' | '/about' | '/' | '/blog/$' | '/blog'
  id:
    | '__root__'
    | '/_public'
    | '/help'
    | '/_public/about'
    | '/_public/blog'
    | '/_public/'
    | '/_public/blog/$'
    | '/_public/blog/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  HelpRoute: typeof HelpRoute
}

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  HelpRoute: HelpRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_public",
        "/help"
      ]
    },
    "/_public": {
      "filePath": "_public.tsx",
      "children": [
        "/_public/about",
        "/_public/blog",
        "/_public/"
      ]
    },
    "/help": {
      "filePath": "help.tsx"
    },
    "/_public/about": {
      "filePath": "_public/about.tsx",
      "parent": "/_public"
    },
    "/_public/blog": {
      "filePath": "_public/blog.tsx",
      "parent": "/_public",
      "children": [
        "/_public/blog/$",
        "/_public/blog/"
      ]
    },
    "/_public/": {
      "filePath": "_public/index.tsx",
      "parent": "/_public"
    },
    "/_public/blog/$": {
      "filePath": "_public/blog.$.tsx",
      "parent": "/_public/blog"
    },
    "/_public/blog/": {
      "filePath": "_public/blog.index.tsx",
      "parent": "/_public/blog"
    }
  }
}
ROUTE_MANIFEST_END */
